CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  prenom VARCHAR(100),
  nom VARCHAR(100),
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Joueurs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  User_id INT UNIQUE NOT NULL,
  Equipe_id INT NULL,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS Selectionneurs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  User_id INT UNIQUE NOT NULL,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Organisateurs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  User_id INT UNIQUE NOT NULL,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  User_id INT UNIQUE NOT NULL,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Equipes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL UNIQUE,
  Selectionneurs_id INT NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Selectionneurs_id) REFERENCES Selectionneurs(User_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Tournois (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  date_debut DATE NOT NULL,
  lieu VARCHAR(100) NOT NULL,
  Organisateurs_id INT,
  lancer BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Organisateurs_id) REFERENCES Organisateurs(User_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Participants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Equipe_id INT NOT NULL,
  Tournois_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Tournois_id) REFERENCES Tournois(id) ON DELETE CASCADE,
  FOREIGN KEY (Equipe_id) REFERENCES Equipes(id) ON DELETE CASCADE,
  CONSTRAINT unique_equipe_tournoi UNIQUE (Equipe_id, Tournois_id)
);

CREATE TABLE IF NOT EXISTS Matchs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_heure DATETIME NOT NULL,
  lieu VARCHAR(100) NOT NULL,
  tour INT,
  Equipe1_id INT DEFAULT NULL,
  Equipe2_id INT DEFAULT NULL,
  prolongation BOOLEAN DEFAULT FALSE,
  Tournois_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Equipe1_id) REFERENCES Equipes(id) ON DELETE CASCADE,
  FOREIGN KEY (Equipe2_id) REFERENCES Equipes(id) ON DELETE CASCADE,
  FOREIGN KEY (Tournois_id) REFERENCES Tournois(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Buts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_heure DATETIME,
  User_id INT NOT NULL,
  Match_id INT NOT NULL,
  Type_But BOOLEAN NOT NULL,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (Match_id) REFERENCES Matchs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expediteur_id INT NOT NULL,
  destinataire_id INT NOT NULL,
  message TEXT NOT NULL,
  lu BOOLEAN DEFAULT FALSE,
  date_envoi DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (expediteur_id) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (destinataire_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Groupes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Owner_id INT NOT NULL,
  nom VARCHAR(100) NOT NULL UNIQUE,
  FOREIGN KEY (Owner_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Groupes_Membres (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Groupe_id INT,
  User_id INT,
  FOREIGN KEY (Groupe_id) REFERENCES Groupes(id) ON DELETE CASCADE,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE,
  CONSTRAINT uniquie UNIQUE (User_id, Groupe_id)
);

CREATE TABLE IF NOT EXISTS Groupes_Messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expediteur_id INT NOT NULL,
  Groupe_id INT NOT NULL,
  message TEXT NOT NULL,
  date_envoi DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (expediteur_id) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (Groupe_id) REFERENCES Groupes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Forms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  prenom VARCHAR(100) NOT NULL,
  nom VARCHAR(100) NOT NULL,
  Utype VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);