CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  prenom VARCHAR(100) NOT NULL,
  nom VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS Joueurs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  User_id INT UNIQUE NOT NULL,
  Equipe_id INT NULL,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS Selectionneurs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  User_id INT UNIQUE NOT NULL,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Organisateurs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  User_id INT UNIQUE NOT NULL,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Equipes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL UNIQUE,
  Selectionneurs_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Selectionneurs_id) REFERENCES Selectionneurs(User_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Tournois (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  date_debut DATETIME NOT NULL,
  lieu VARCHAR(100) NOT NULL,
  Organisateurs_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Organisateurs_id) REFERENCES Organisateurs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Matchs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_heure DATETIME NOT NULL,
  lieu VARCHAR(100) NOT NULL,
  Equipe1_id INT NOT NULL,
  Equipe2_id INT NOT NULL,
  score VARCHAR(100) DEFAULT NULL,
  Tournois_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Tournois_id) REFERENCES Tournois(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expediteur_id INT NOT NULL,
  destinataire_id INT NOT NULL,
  message TEXT NOT NULL,
  date_envoi DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (expediteur_id) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (destinataire_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Groupes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Groupes_Membres (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Groupes_id INT,
  User_id INT,
  FOREIGN KEY (Groupes_id) REFERENCES Groupes(id) ON DELETE CASCADE,
  FOREIGN KEY (User_id) REFERENCES User(id) ON DELETE CASCADE
);
